before_install: cd StandOrganizer.App
language: node_js
node_js:
  - "6.9"
  - "7.1"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  - NODE_ENV='test'
script:
  - npm run lint
  - npm test